[AccessTransformers]

; Expose the Customization Material mapping array so we can do CDO injection
BlueprintReadWrite=(Class="/Script/FactoryGame.FGFactoryCustomizationDescriptor_Material", Property="mBuildableMap")

; Expose schematic unlock array to inject pine into 1-1
BlueprintReadWrite=(Class="/Script/FactoryGame.FGSchematic", Property="mUnlocks")
